### ISSUE TITLE
Could not find a version that satisfies the requirement motion-vector-extractor

### ISSUE THREAD

**Issue by whmc76** [chaojie/ComfyUI-LaVIT#1]
ERROR: Could not find a version that satisfies the requirement motion-vector-extractor (from versions: none)
ERROR: No matching distribution found for motion-vector-extractor

**Comment by feifeiye** [comment]
I met the same problem, have you solved it?

**Comment by whmc76** [comment]
> I met the same problem, have you solved it?

没有 google也没找到这个 在pip里面看是空的

**Comment by chaojie** [comment]
@whmc76 @feifeiye I removed motion-vector-extractor from requirements.txt and modified the code. It should be fixed. You can have a try.

**Comment by feifeiye** [comment]
Thanks, it's already installed
